### ISSUE TITLE
Add info about intgen dependency

### ISSUE THREAD

**Issue by olofk** [stffrdhrn/mor1kx-generic#2]
mor1kx-generic depends on intgen. It would be good to either have a note in the readme file on how to get intgen (i.e. `fusesoc library add intgen https://github.com/stffrdhrn/intgen`) or just drop in an intgen .core file directly into this repo if it's primary usecase is inside of mor1kx-generic

**Comment by olofk** [comment]
Opened #3 for this

**Comment by stffrdhrn** [comment]
Thanks, I am not sure why I never saw this.  Github doesn't notify me for some reason

**Comment by stffrdhrn** [comment]
Mergedd
